version: "3.1"
services:
  guestbook_db:
        container_name: mariadb
        image: mariadb
        restart: always
        environment:
          MYSQL_DATABASE: guestbook
          MYSQL_ROOT_PASSWORD: 123123
          MYSQL_ROOT_HOST: '%'
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        ports:
          - 3306:3306
        volumes:
          - ${PWD}/docker/mariadb/var/lib/mysql:/var/lib/mysql
          - ${PWD}/docker/mariadb/var/log/maria:/var/log/maria
        
